# -*- coding: utf-8 -*-

{
    'name': 'Personnalisation MADATA',
    'version': '15.0.1.1.0',
    'category': 'Uncategorized',
    'summary': """
        ADISA Addons Modules
    """,
    'description': """Odoo 15 Customs Modules""",
    'author': 'SMoussa',
    'company': 'ADISA',
    'maintainer': 'ADISA',
    'website': 'https://www.adisa.digital',
    'depends': ['base','crm', 'sale','purchase','stock','hr_contract','hr_holidays', 'product','account','analytic','hr_expense','hr',
                'hr_expense','hr_payroll','hr_update','ctp_customize_title','sale_management','sale_stock'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/prepa_liv.xml',
        # 'views/secteur_activite.xml',
        'views/activite_entreprise.xml',
        'views/categorie_societe.xml',
        'views/res_partner.xml',
        'views/res_users.xml',
        # 'views/product_update.xml',
        # 'views/prepa_livraison.xml',
        # 'views/crm_affaire.xml',
        # 'views/prepa_livraison.xml',
        # 'views/prepa_livraison_gm.xml',
        # 'views/pilotage_materiel.xml',
        # 'views/pilotage_produit.xml',
        # 'views/pilotage_prod.xml',
        # 'views/prepa_livraison.xml',
        # 'views/x_bon_preparation_livraison.xml',
        # 'views/x_bon_livraison.xml',
        # 'views/suivi_affaires.xml',
        # 'views/stock_commande.xml',
        'views/account_move_custom.xml',
        # 'views/product_template_customer_view.xml',
        # 'wizard/invoice_custom_views.xml',
        # 'views/sale_order_customers_view.xml',
        # 'views/purchase_order_custom_view.xml',
        # 'views/sortie_materiel.xml',
        # 'views/achat_materiel.xml',
        # 'views/facture_materiel.xml',
        'views/taux_configuration.xml',
        # 'views/affaire_pl_stock.xml',
        'views/centralisation_tva.xml',
        # 'views/hr_employee.xml',
        # 'views/employee_reports.xml',
        # 'views/hr_payslip.xml',
        # 'views/hr_contract.xml',
        'views/account_analytic_custom_view.xml',
        'views/icon_module.xml',
        'views/hr_expense_sheet.xml',
        'views/hr_expense_custom_view.xml',
        'views/hr_expense_request.xml',
        'views/account_bank_statement_view.xml',
        # 'views/account_bank_statement_views.xml',
        # 'views/panier_achat.xml',
        # 'wizard/choix_fournisseur.xml',
        # 'views/stock_picking_view.xml',
        'report/template_delivery.xml',
        # 'report/stock_report_views1.xml',
        #'report/report_invoice_custom.xml',
        'report/report_attestation_conges.xml',
        'report/report_attestation_travail.xml',
        'report/report_certificat_travail.xml',
        'report/report_piece_caisse.xml',
        'report/report_hr_expense_wizard.xml',
        'wizard/expense_sheet_wizard.xml',
        'views/website_templates.xml', 
        'views/login.xml',    
    ],
    'installable': True,
    'images': ['static/description/banner.png'],
    'auto_install': False,
    'application': False,
    'license': 'AGPL-3',
}
